apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-a-2329145
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-a-2329145
  template:
    metadata:
      labels:
        app: devops-a-2329145
    spec:
      containers:
        - name: devops-a-2329145
          image: devops-a-2329145:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80